import { jsPDF } from 'jspdf'
import { groupAdminAttendanceMeetings, summarizeAdminAttendanceOverall, summarizeAdminAttendanceStudents, type AdminAttendanceRecord } from '../services/admin-attendance.service'

export type AdminAttendancePdfReport = {
  records: AdminAttendanceRecord[]
  generatedBy: string
  generatedAt: string
  filters: { student: string, teacher: string, teachingGroup: string, period: string }
  filename: string
}

const left = 14
const right = 196

function date(value: string) { return new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${value.slice(0, 10)}T00:00:00`)) }
function time(value: string) { return new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(value)) }
function rate(value: number | null) { return value === null ? '-' : `${value.toFixed(1)}%` }
function packageType(value: AdminAttendanceRecord['package_type']) { return value === 'semi_private' ? 'Semi-private' : 'Private' }

function heading(doc: jsPDF, text: string, y: number) {
  doc.setFillColor(15, 23, 42); doc.rect(left, y, right - left, 8, 'F')
  doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.text(text, left + 3, y + 5.3)
  doc.setTextColor(0, 0, 0); doc.setFont('helvetica', 'normal')
  return y + 12
}

function attendanceHeader(doc: jsPDF, y: number) {
  doc.setFillColor(241, 245, 249); doc.rect(left, y, right - left, 7, 'F')
  doc.setFont('helvetica', 'bold'); doc.setFontSize(7)
  ;[['Student', 17], ['Code', 80], ['Status', 130]].forEach(([label, x]) => doc.text(String(label), Number(x), y + 4.6))
  doc.setFont('helvetica', 'normal')
  return y + 7
}

function studentSummaryHeader(doc: jsPDF, y: number) {
  doc.setFillColor(241, 245, 249); doc.rect(left, y, right - left, 7, 'F')
  doc.setFont('helvetica', 'bold'); doc.setFontSize(6.5)
  ;[['Student', 17], ['Code', 50], ['Teaching Group', 74], ['Sessions', 118], ['Present', 140], ['Absent', 159], ['Rate', 193]].forEach(([label, x]) => doc.text(String(label), Number(x), y + 4.6, Number(x) > 180 ? { align: 'right' } : undefined))
  doc.setFont('helvetica', 'normal')
  return y + 7
}

export function downloadAdminAttendancePdf(report: AdminAttendancePdfReport) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const bottom = 280
  let y = 14
  const nextPage = () => { doc.addPage(); y = 14 }
  const ensure = (height: number) => { if (y + height > bottom) { nextPage(); return true } return false }
  const meetings = groupAdminAttendanceMeetings(report.records)
  const students = summarizeAdminAttendanceStudents(report.records)
  const overall = summarizeAdminAttendanceOverall(report.records)

  doc.setFont('helvetica', 'bold'); doc.setFontSize(16); doc.text('QUICKSPEAK LMS', left, y)
  doc.setFontSize(12); doc.text('ADMIN ATTENDANCE REPORT', left, y + 7)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8)
  doc.text(`Generated By: ${report.generatedBy}`, left, y + 17); doc.text(`Generated: ${report.generatedAt}`, left, y + 22)
  doc.text(`Student: ${report.filters.student}`, 105, y + 17); doc.text(`Teacher: ${report.filters.teacher}`, 105, y + 22)
  doc.text(`Group: ${report.filters.teachingGroup}`, left, y + 27); doc.text(`Period: ${report.filters.period}`, 105, y + 27)
  y += 35

  y = heading(doc, 'A. MEETING & ATTENDANCE DETAIL', y)
  if (meetings.length === 0) { doc.setFontSize(9); doc.text('No attendance records match the active filters.', left, y); y += 8 }
  meetings.forEach((meeting) => {
    if (ensure(27)) y = heading(doc, 'A. MEETING & ATTENDANCE DETAIL (CONTINUED)', y)
    doc.setFillColor(248, 250, 252); doc.rect(left, y, right - left, 20, 'F')
    doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.text(`${date(meeting.session_date)} - ${time(meeting.teacher_recorded_at)}`, left + 3, y + 5)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(7)
    doc.text(`Teaching Group: ${meeting.teaching_group_name}`, left + 3, y + 10); doc.text(`Teacher: ${meeting.teacher_name} (${meeting.teacher_code})`, 92, y + 10)
    doc.text(`Level: ${meeting.level_name}`, left + 3, y + 15); doc.text(`Package: ${packageType(meeting.package_type)}`, 92, y + 15)
    y = attendanceHeader(doc, y + 20)
    meeting.records.forEach((record) => {
      if (ensure(7)) y = attendanceHeader(doc, y)
      doc.setDrawColor(226, 232, 240); doc.line(left, y + 7, right, y + 7); doc.setFontSize(7)
      doc.text(doc.splitTextToSize(record.student_name, 59) as string[], 17, y + 4.5); doc.text(record.student_code, 80, y + 4.5); doc.text(record.teacher_status === 'present' ? 'Present' : 'Absent', 130, y + 4.5)
      y += 7
    })
    y += 4
  })

  if (ensure(25)) nextPage()
  y = heading(doc, 'B. STUDENT ATTENDANCE SUMMARY', y); y = studentSummaryHeader(doc, y)
  students.forEach((student) => {
    if (ensure(8)) { y = heading(doc, 'B. STUDENT ATTENDANCE SUMMARY (CONTINUED)', y); y = studentSummaryHeader(doc, y) }
    doc.setDrawColor(226, 232, 240); doc.line(left, y + 8, right, y + 8); doc.setFontSize(6.5)
    doc.text(doc.splitTextToSize(student.student_name, 30) as string[], 17, y + 4.7); doc.text(student.student_code, 50, y + 4.7); doc.text(doc.splitTextToSize(student.teaching_group_name, 40) as string[], 74, y + 4.7)
    doc.text(String(student.total_sessions), 120, y + 4.7); doc.text(String(student.present), 142, y + 4.7); doc.text(String(student.absent), 161, y + 4.7); doc.text(rate(student.attendance_rate), 193, y + 4.7, { align: 'right' }); y += 8
  })

  if (ensure(38)) nextPage()
  y = heading(doc, 'C. OVERALL ATTENDANCE SUMMARY', y)
  doc.setFillColor(248, 250, 252); doc.rect(left, y, right - left, 24, 'F'); doc.setFontSize(8)
  doc.text(`Total Sessions: ${overall.total_sessions}`, left + 4, y + 7); doc.text(`Total Attendance Records: ${overall.total_records}`, 76, y + 7)
  doc.text(`Total Present: ${overall.present}`, left + 4, y + 14); doc.text(`Total Absent: ${overall.absent}`, 76, y + 14); doc.text(`Overall Attendance Rate: ${rate(overall.attendance_rate)}`, 135, y + 14)

  const pages = doc.getNumberOfPages()
  for (let pageNumber = 1; pageNumber <= pages; pageNumber += 1) {
    doc.setPage(pageNumber); doc.setDrawColor(226, 232, 240); doc.line(left, 286, right, 286); doc.setFontSize(7); doc.setTextColor(100, 116, 139)
    doc.text(`QuickSpeak LMS - Admin Attendance Report - Generated ${report.generatedAt}`, left, 290); doc.text(`Page ${pageNumber} of ${pages}`, right, 290, { align: 'right' }); doc.setTextColor(0, 0, 0)
  }
  doc.save(report.filename)
}
